# Generated by Django 4.2.4 on 2023-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTinDatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('dia_chi', models.CharField(max_length=200)),
                ('du_doan', models.CharField(choices=[('SPAM', 'Người dùng Spam'), ('ACTUAL', 'Người dùng thực tế')], default='ACTUAL', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('gui_tu_url', models.CharField(blank=True, max_length=200, null=True)),
                ('thoi_gian_gui', models.DateTimeField(auto_now_add=True)),
                ('ten_san_pham', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-thoi_gian_gui'],
                'indexes': [models.Index(fields=['ten', 'so_dien_thoai'], name='store_thong_ten_e2581a_idx')],
            },
        ),
    ]
